// <auto-generated />
using DMSEntityFrameWork;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DMSEntityFrameWork.Migrations
{
    [DbContext(typeof(DoctorDBContext))]
    [Migration("20241212094511_Initial9")]
    partial class Initial9
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DMSEntityFrameWork.Models.Doctor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("qualification")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("specialisation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("DMSEntityFrameWork.Models.Patient", b =>
                {
                    b.Property<int>("pId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("pId"));

                    b.Property<int>("id")
                        .HasColumnType("integer");

                    b.Property<string>("pDisease")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("pName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("pId");

                    b.HasIndex("id");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("DMSEntityFrameWork.Models.Patient", b =>
                {
                    b.HasOne("DMSEntityFrameWork.Models.Doctor", "Doctor")
                        .WithMany("Patients")
                        .HasForeignKey("id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("DMSEntityFrameWork.Models.Doctor", b =>
                {
                    b.Navigation("Patients");
                });
#pragma warning restore 612, 618
        }
    }
}
