// <auto-generated />
using System;
using CoreApiEFProject;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoreApiEFProject.Migrations
{
    [DbContext(typeof(PetDBContext))]
    [Migration("20241224055339_initialserve1")]
    partial class initialserve1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoreApiEFProject.Model.PetAnimal", b =>
                {
                    b.Property<int>("petId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("petId"));

                    b.Property<DateTime>("petDob")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("petIsVeg")
                        .HasColumnType("boolean");

                    b.Property<string>("petName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("petType")
                        .HasColumnType("text");

                    b.HasKey("petId");

                    b.ToTable("PetAnimals");
                });
#pragma warning restore 612, 618
        }
    }
}
